/**
 * Edit this file to expand scenarios, stage copy, unlock conditions, and mode behavior.
 * All gameplay content is data-driven from here.
 */
export const MODES = {
  standard: {
    id: "standard",
    title: "Standard",
    description: "Balanced visibility. Serious but fair.",
    timeMultiplier: 1,
    infoPenalty: 0,
    scoreMultiplier: 1,
  },
  hard: {
    id: "hard",
    title: "Hard",
    description: "Tighter margins, harsher consequences, less slack.",
    timeMultiplier: 0.85,
    infoPenalty: 0.08,
    scoreMultiplier: 1.15,
  },
  "low-information": {
    id: "low-information",
    title: "Low-Information",
    description: "You see less context and must infer more.",
    timeMultiplier: 1,
    infoPenalty: 0.2,
    scoreMultiplier: 1.2,
  },
  "high-pressure": {
    id: "high-pressure",
    title: "High-Pressure",
    description: "Time compresses. Your decisions still compound.",
    timeMultiplier: 0.65,
    infoPenalty: 0.05,
    scoreMultiplier: 1.25,
  },
  "ethics-stress-test": {
    id: "ethics-stress-test",
    title: "Ethics Stress Test",
    description: "Many options look efficient but erode integrity.",
    timeMultiplier: 0.9,
    infoPenalty: 0.1,
    scoreMultiplier: 1.22,
  },
  "long-horizon-strategist": {
    id: "long-horizon-strategist",
    title: "Long-Horizon Strategist",
    description: "Delayed consequences carry more weight than short-term relief.",
    timeMultiplier: 1,
    infoPenalty: 0.05,
    scoreMultiplier: 1.25,
  },
};

export const STAT_INFO = {
  resilience: "Capacity to absorb shocks without spiraling.",
  adaptability: "Ability to pivot when the environment changes.",
  focus: "Ability to allocate attention under noise and pressure.",
  "mental-stamina": "Tolerance for sustained ambiguity and stress.",
  credibility: "Whether others believe your judgment.",
  "network-trust": "Strength of reciprocal professional and social ties.",
  "financial-buffer": "Months of margin before scarcity dominates decisions.",
  "learning-velocity": "Speed of acquiring useful new capability.",
  "health-stability": "Sleep, routine, energy, and recovery integrity.",
  "strategic-clarity": "Ability to think in systems and time horizons.",
  "ethical-consistency": "How reliably your values hold under incentives.",
  "ai-reliance": "Dependence on automation beyond prudent leverage.",
};

export const STAGE_META = [
  {
    id: "personal-stability",
    title: "Personal Stability",
    summary: "Housing, health, routines, and identity under pressure.",
  },
  {
    id: "career-disruption",
    title: "Career Disruption",
    summary: "AI displacement, skill pivots, and career fragility.",
  },
  {
    id: "financial-stress",
    title: "Financial Stress",
    summary: "Income loss, traps, liquidity stress, and capital allocation.",
  },
  {
    id: "social-trust",
    title: "Social Trust & Reputation",
    summary: "Misinformation, network erosion, and reputational ambiguity.",
  },
  {
    id: "crisis-leadership",
    title: "Crisis Leadership",
    summary: "Leading under system shocks, triage, and partial information.",
  },
  {
    id: "strategic-survival",
    title: "2050 Strategic Survival",
    summary: "Long-range planning, tradeoffs, and civilizational uncertainty.",
  },
];

export const STAGES = [
  {
    id: "personal-stability",
    title: "Personal Stability",
    intro: "The first future shock is not abstract technology. It is whether your body, home, and routine can survive volatility without silent collapse.",
    levels: [
      {
        id: "ps1-housing-burn",
        title: "Fragile Apartment, Fragile Routine",
        type: "decision",
        year: 2026,
        difficulty: 1,
        timed: false,
        briefing: {
          objective: "Choose a housing response to rising rent, longer commute risk, and worsening sleep.",
          constraints: ["Savings are thin", "Your work requires concentration", "Family support is limited but not zero"],
          resources: ["₹1.6 lakh liquid cash", "One dependable friend nearby", "A manager who values output but not excuses"],
          scoring: "You gain more for preserving stability and flexibility than for preserving status.",
          outcomes: {
            success: "You preserve sleep, flexibility, and cost runway.",
            partial: "You solve one problem but create another drag.",
            failure: "Short-term image wins, long-term stability cracks.",
          },
        },
        scenario: "Rent on your current city apartment jumps 28%. You already sleep badly and your work quality has slipped. A prestige move keeps appearances intact but eats your buffer. Moving farther away lowers costs but increases commute fatigue. Shared housing is emotionally unappealing but materially stabilizing.",
        options: [
          {
            id: "shared-flat",
            title: "Move into a modest shared flat for 9 months",
            description: "Lower ego comfort now, recover cash runway and sleep discipline.",
            effects: { "financial-buffer": 12, health-stability: 8, resilience: 7, credibility: -1, focus: 6 },
            tags: ["adaptive", "anti-fragile"],
            rationale: "You intentionally lower lifestyle vanity to recover maneuvering room.",
          },
          {
            id: "stay-and-stretch",
            title: "Stay in place and stretch finances",
            description: "Avoid disruption, but monthly anxiety rises immediately.",
            effects: { "financial-buffer": -14, health-stability: -4, focus: -5, credibility: 2, resilience: -6 },
            tags: ["status-preserving", "fragile"],
            rationale: "You preserve appearances but reduce future choice.",
          },
          {
            id: "far-commute",
            title: "Move far out for solo privacy and lower rent",
            description: "Costs fall but friction and fatigue increase.",
            effects: { "financial-buffer": 7, health-stability: -5, focus: -4, adaptability: 3, resilience: 1 },
            tags: ["mixed"],
            rationale: "Financially better than staying, but daily energy leakage compounds.",
          },
        ],
      },
      {
        id: "ps2-health-stack",
        title: "Health Stack Collapse",
        type: "allocation",
        year: 2028,
        difficulty: 2,
        timed: true,
        timeLimit: 55,
        briefing: {
          objective: "Allocate six recovery points across habits before your baseline breaks.",
          constraints: ["You have exactly 6 points", "Each choice trades performance now vs health later", "Work remains demanding"],
          resources: ["Flexible mornings", "No extra money for premium services", "You can say no to some commitments"],
          scoring: "Balanced, durable recovery beats extreme optimization in one area.",
          outcomes: {
            success: "You create a stable operating rhythm that compounds.",
            partial: "You patch symptoms but not the system.",
            failure: "You maximize visible productivity while health debt deepens.",
          },
        },
        scenario: "You are not in crisis, which is why this level is dangerous. You are drifting into chronic fatigue: poor sleep, over-caffeination, missed exercise, irregular meals, constant reactive phone use.",
        pool: 6,
        choices: [
          { id: "sleep", label: "Sleep protection", cost: 2, effects: { "health-stability": 10, "mental-stamina": 4, focus: 3 } },
          { id: "exercise", label: "Training / mobility", cost: 2, effects: { resilience: 5, "health-stability": 7, focus: 2 } },
          { id: "deep-work", label: "Protected deep work blocks", cost: 1, effects: { focus: 8, "strategic-clarity": 3 } },
          { id: "social", label: "Weekly human support time", cost: 1, effects: { resilience: 4, "network-trust": 5, "mental-stamina": 2 } },
          { id: "meal", label: "Meal regularity", cost: 1, effects: { "health-stability": 5, focus: 2 } },
          { id: "notifications", label: "Aggressive notification pruning", cost: 1, effects: { focus: 5, adaptability: 2 } },
        ],
        rationale: "Recovery is not decorative. It is part of strategic capacity.",
      },
      {
        id: "ps3-identity-shock",
        title: "Identity After a Public Setback",
        type: "priority",
        year: 2030,
        difficulty: 3,
        timed: true,
        timeLimit: 45,
        briefing: {
          objective: "Rank your first-response priorities after a visible failure.",
          constraints: ["You must rank all five actions", "Fast emotional relief may conflict with long-term repair"],
          resources: ["A small amount of goodwill", "Two people still trust you deeply", "No guarantee the market will forgive quickly"],
          scoring: "The best order protects function first, narrative second, ego last.",
          outcomes: {
            success: "You stabilize reality before trying to repair image.",
            partial: "You do some real repair but get distracted by optics.",
            failure: "You chase public reassurance while internal breakdown worsens.",
          },
        },
        scenario: "A product you led failed publicly. Online criticism is piling on. You feel shame, anger, and urgency. You have one evening before investors, colleagues, and family start calling with their own interpretations.",
        items: [
          { id: "sleep", label: "Get one protected night of sleep before replying widely", idealRank: 2, effects: { "mental-stamina": 5, focus: 4 } },
          { id: "facts", label: "Write a one-page private facts memo: what actually happened", idealRank: 1, effects: { "strategic-clarity": 8, credibility: 3 } },
          { id: "mentor", label: "Call two trusted people who will not flatter you", idealRank: 3, effects: { resilience: 4, "network-trust": 5 } },
          { id: "public", label: "Post a fast public thread to reclaim the narrative", idealRank: 5, effects: { credibility: -3, focus: -3, "ai-reliance": 1 } },
          { id: "blame", label: "Privately draft who else is responsible", idealRank: 4, effects: { "ethical-consistency": -6, credibility: -4 } },
        ],
        rationale: "In a hit to identity, sequencing matters as much as choice.",
      },
    ],
    debrief: "Stability is not softness. It is the infrastructure that lets you take hard hits without losing agency.",
  },
  {
    id: "career-disruption",
    title: "Career Disruption",
    intro: "The market no longer rewards static competence. It rewards people who can reconfigure themselves without losing judgment.",
    levels: [
      {
        id: "cd1-automation-wave",
        title: "Your Role Is Being Compressed",
        type: "decision",
        year: 2031,
        difficulty: 2,
        timed: false,
        briefing: {
          objective: "Pick a response to role compression from multimodal AI systems.",
          constraints: ["You cannot do everything at once", "Your current title is losing bargaining power", "Income still matters now"],
          resources: ["Strong work ethic", "Weak portfolio outside current role", "One year before the market fully reprices this skill"],
          scoring: "The best response increases leverage and learning, not just panic activity.",
          outcomes: {
            success: "You reposition toward hard-to-automate value while staying solvent.",
            partial: "You work hard but mostly defend the old map.",
            failure: "You confuse motion with adaptation.",
          },
        },
        scenario: "Your function is not gone, but the market now expects one person with AI systems to do the work of three. Promotions shrink. Fees drop. Senior people deny the shift in public and privately cut headcount.",
        options: [
          {
            id: "pivot-stack",
            title: "Keep income, but build a portfolio in AI-adjacent execution",
            description: "Shift 10 hours/week into workflow design, judgment-heavy coordination, and proof-of-work.",
            effects: { adaptability: 10, "learning-velocity": 9, "financial-buffer": 2, focus: -2 },
            tags: ["durable", "disciplined"],
            rationale: "You protect cash while building evidence in a higher-value layer.",
          },
          {
            id: "double-down-old",
            title: "Become the absolute best in the old specialty",
            description: "Refine mastery and hope premium niches remain.",
            effects: { focus: 5, adaptability: -8, "learning-velocity": -5, credibility: 2 },
            tags: ["high-variance"],
            rationale: "Could work for a few, but broad market repricing still hurts.",
          },
          {
            id: "quit-and-study",
            title: "Quit immediately and spend savings on a full reset",
            description: "Maximum learning intensity, maximum cash risk.",
            effects: { "learning-velocity": 12, "financial-buffer": -12, resilience: -4, adaptability: 8 },
            tags: ["bold", "fragile"],
            rationale: "Only works if your runway and execution discipline are strong enough.",
          },
        ],
      },
      {
        id: "cd2-signal-vs-noise",
        title: "Credential or Capability?",
        type: "contradiction",
        year: 2034,
        difficulty: 3,
        timed: true,
        timeLimit: 60,
        briefing: {
          objective: "Select the three signals that most credibly indicate durable career opportunity.",
          constraints: ["Choose exactly 3", "Not all polished signals matter", "Some options are intentionally seductive noise"],
          resources: ["One month to decide where to invest your effort", "Moderate online reach", "No elite credential advantage"],
          scoring: "You score higher for spotting genuine leverage and lower for prestige theater.",
          outcomes: {
            success: "You invest in signals that map to real demand and repeatable value.",
            partial: "You catch some truth but still overpay for optics.",
            failure: "You chase badges detached from actual market power.",
          },
        },
        scenario: "You are comparing multiple pivot paths. Every path markets itself as future-proof. Most are not.",
        correctIds: ["proof", "distribution", "compound-skill"],
        choices: [
          { id: "proof", title: "Public proof-of-work that solves costly problems", description: "Case studies, shipped systems, measurable before/after." },
          { id: "badge", title: "Prestige certificate from a hot platform", description: "Widely marketed, easy to display, hard to distinguish." },
          { id: "distribution", title: "Reliable access to customers, audiences, or decision-makers", description: "Distribution compounds skill into opportunity." },
          { id: "trend", title: "Frequent posting about every new AI trend", description: "Looks current, often lacks substance." },
          { id: "compound-skill", title: "Combination of domain judgment + technical fluency + trust", description: "Hard to automate and hard to fake." },
          { id: "hours", title: "Long hours logged on learning dashboards", description: "Activity is not necessarily market value." },
        ],
        rationale: "Future resilience comes from scarce combinations, not decorative credentials.",
      },
      {
        id: "cd3-managerial-pivot",
        title: "You Lead a Human + AI Team Now",
        type: "decision",
        year: 2037,
        difficulty: 4,
        timed: false,
        briefing: {
          objective: "Choose how to manage a team whose output is partly automated and partly human judgment.",
          constraints: ["Cost pressure is real", "Morale is fragile", "Accuracy errors still matter"],
          resources: ["Good operator instincts", "A skeptical team", "One quarter to prove the model"],
          scoring: "The strongest answer balances throughput, oversight, and trust calibration.",
          outcomes: {
            success: "You design a team that uses AI as force multiplier without losing judgment integrity.",
            partial: "You improve throughput but degrade trust or quality.",
            failure: "You either over-automate blindly or refuse adaptation entirely.",
          },
        },
        scenario: "Your company wants 40% more throughput with the same budget. Some staff quietly rely on AI for everything. Others refuse to touch it and are now bottlenecks. A bad output last month damaged client confidence.",
        options: [
          {
            id: "audit-layers",
            title: "Redesign workflow with human judgment checkpoints on high-risk outputs",
            description: "Automate low-risk work, audit critical thinking paths, train staff on escalation.",
            effects: { credibility: 8, adaptability: 7, "ai-reliance": -2, "strategic-clarity": 6 },
            tags: ["systems-thinking"],
            rationale: "You separate where speed matters from where judgment must dominate.",
          },
          {
            id: "full-automation",
            title: "Push aggressive automation targets across the board",
            description: "Fast short-term gains, fragile error surface.",
            effects: { "financial-buffer": 6, credibility: -7, "ai-reliance": 10, "network-trust": -4 },
            tags: ["efficient", "brittle"],
            rationale: "Looks decisive, but one serious miss can erase savings.",
          },
          {
            id: "protect-old",
            title: "Keep humans doing most tasks manually to preserve quality",
            description: "Trust may hold, but cost competitiveness worsens fast.",
            effects: { credibility: 3, adaptability: -9, "financial-buffer": -5, focus: -2 },
            tags: ["safe-feeling", "erosive"],
            rationale: "Defensive comfort can quietly destroy viability.",
          },
        ],
      },
    ],
    debrief: "Career resilience is usually not about one giant leap. It is about repeated sober pivots before the market forces humiliation.",
  },
  {
    id: "financial-stress",
    title: "Financial Stress",
    intro: "Money is not only a return game. In unstable eras it is a time, options, and dignity game.",
    levels: [
      {
        id: "fs1-cash-crunch",
        title: "Four Months of Runway",
        type: "allocation",
        year: 2032,
        difficulty: 2,
        timed: true,
        timeLimit: 50,
        briefing: {
          objective: "Allocate ten budget units across immediate needs to survive a sudden income drop.",
          constraints: ["You have only 10 units", "Underfunding some categories creates hidden penalties", "This is about survival quality, not comfort"],
          resources: ["Small emergency fund", "No debt yet", "Uncertain freelance pipeline"],
          scoring: "The strongest budget protects runway, health, and earning capacity simultaneously.",
          outcomes: {
            success: "You preserve optionality while staying physically and mentally functional.",
            partial: "You survive, but with growing hidden fragility.",
            failure: "You underinvest in the foundations that let income recover.",
          },
        },
        scenario: "A client collapse cuts your income by 45%. You must rebuild cash discipline immediately without making yourself unemployable or physically unstable.",
        pool: 10,
        choices: [
          { id: "rent", label: "Housing / rent", cost: 3, effects: { "financial-buffer": 4, resilience: 2 } },
          { id: "food", label: "Nutrition and basic groceries", cost: 2, effects: { "health-stability": 7, focus: 2 } },
          { id: "network", label: "Relationship maintenance / networking", cost: 1, effects: { "network-trust": 6, credibility: 2 } },
          { id: "skill", label: "Skill / tooling upkeep", cost: 1, effects: { "learning-velocity": 6, adaptability: 3 } },
          { id: "transport", label: "Mobility / transport", cost: 1, effects: { focus: 2, resilience: 1 } },
          { id: "buffer", label: "Pure liquidity reserve", cost: 2, effects: { "financial-buffer": 9, "mental-stamina": 2 } },
          { id: "status", label: "Status expenses you are embarrassed to cut", cost: 2, effects: { credibility: 1, "financial-buffer": -7, resilience: -5 } },
        ],
        rationale: "Scarcity punishes ego-driven spending faster than almost anything else.",
      },
      {
        id: "fs2-investment-traps",
        title: "Signal, Story, or Trap?",
        type: "contradiction",
        year: 2035,
        difficulty: 3,
        timed: true,
        timeLimit: 55,
        briefing: {
          objective: "Select the three strongest red flags in a supposedly 'defensive' investment pitch.",
          constraints: ["Choose exactly 3", "The pitch mixes truth with manipulation", "You are under pressure to recover losses"],
          resources: ["Basic investing knowledge", "A recent loss that makes you emotionally vulnerable", "No urgent need to deploy capital today"],
          scoring: "You score higher for detecting structural risk, not just obvious hype language.",
          outcomes: {
            success: "You resist narrative seduction and preserve capital discipline.",
            partial: "You catch surface hype but miss deeper misalignment.",
            failure: "You invest based on emotional relief and borrowed confidence.",
          },
        },
        scenario: "A charismatic founder pitches a 'future-proof yield vehicle' tied to climate adaptation infrastructure and AI-optimized logistics. The deck is polished. The terms are not.",
        correctIds: ["illiquid", "guaranteed", "misaligned"],
        choices: [
          { id: "illiquid", title: "Capital lock-up is long and exit rights are vague", description: "You bear timing risk with limited control." },
          { id: "guaranteed", title: "Returns are framed as near-guaranteed in a volatile sector", description: "Certainty language hides risk rather than removing it." },
          { id: "misaligned", title: "Manager fees are high regardless of performance quality", description: "Their upside is protected even when yours is not." },
          { id: "famous", title: "A famous advisor is shown on the slide deck", description: "Not necessarily meaningful without direct responsibility." },
          { id: "technical", title: "The technical model sounds complex", description: "Complexity alone is not evidence of fraud." },
          { id: "niche", title: "It targets a niche future sector", description: "Niche can be good or bad depending on structure." },
        ],
        rationale: "In stressed periods, people often buy confidence, not assets.",
      },
      {
        id: "fs3-family-obligation",
        title: "Your Buffer Is Not Just Yours",
        type: "decision",
        year: 2038,
        difficulty: 4,
        timed: false,
        briefing: {
          objective: "Respond to a family financial emergency without destroying your own viability.",
          constraints: ["The need is real", "Unlimited sacrifice creates second-order risk", "Guilt is distorting your math"],
          resources: ["Moderate savings", "Some earning potential", "No guarantee others in the family will contribute fairly"],
          scoring: "The best answer helps materially while protecting long-term capacity and boundaries.",
          outcomes: {
            success: "You support without self-erasure.",
            partial: "You help, but at serious cost to future resilience.",
            failure: "You respond from guilt alone and create a larger later crisis.",
          },
        },
        scenario: "A parent needs urgent help after a failed business guarantee. The amount is large enough to damage your own runway. Social pressure says 'family first'. Reality says one collapse can become two.",
        options: [
          {
            id: "bounded-support",
            title: "Provide bounded support plus a restructuring plan",
            description: "Contribute a fixed amount, protect an emergency floor, insist on transparency and changes.",
            effects: { "financial-buffer": -4, "ethical-consistency": 6, resilience: 5, "strategic-clarity": 6 },
            tags: ["hard-kindness"],
            rationale: "Support is real, but so are limits.",
          },
          {
            id: "empty-savings",
            title: "Liquidate most savings to solve it quickly",
            description: "Emotionally satisfying now, highly dangerous later.",
            effects: { "financial-buffer": -15, resilience: -6, "network-trust": 2, "mental-stamina": -5 },
            tags: ["sacrificial", "fragile"],
            rationale: "You may buy temporary peace at the cost of your own future crisis.",
          },
          {
            id: "refuse",
            title: "Refuse financial help entirely",
            description: "You preserve runway but risk trust rupture and moral regret.",
            effects: { "financial-buffer": 2, "network-trust": -8, "ethical-consistency": -3, "mental-stamina": -2 },
            tags: ["protective", "cold"],
            rationale: "Not all refusals are wrong, but total disengagement has its own cost.",
          },
        ],
      },
    ],
    debrief: "A financial buffer is stored courage. Once gone, your decision quality is easier to purchase by fear.",
  },
  {
    id: "social-trust",
    title: "Social Trust & Reputation",
    intro: "In fractured information environments, truth, timing, and tone all affect whether people continue to trust you.",
    levels: [
      {
        id: "st1-misinformation",
        title: "The Viral Thread About You",
        type: "priority",
        year: 2033,
        difficulty: 3,
        timed: true,
        timeLimit: 45,
        briefing: {
          objective: "Rank your response priorities to a viral misinformation wave.",
          constraints: ["You must rank all five actions", "Visibility is rising faster than facts", "Every move also signals character"],
          resources: ["You have receipts", "A few credible allies", "Limited energy"],
          scoring: "You score higher by preserving evidence, calm, and selective escalation.",
          outcomes: {
            success: "You protect truth and credibility without feeding the fire blindly.",
            partial: "You defend yourself but waste energy or amplify noise.",
            failure: "You react from panic and worsen the narrative dynamics.",
          },
        },
        scenario: "A clipped video makes you look dishonest. It is spreading faster than corrections. Friends urge immediate response. Enemies want emotional mistakes.",
        items: [
          { id: "archive", label: "Preserve evidence, timestamps, screenshots, and context first", idealRank: 1, effects: { credibility: 6, "strategic-clarity": 4 } },
          { id: "allies", label: "Privately brief 2–3 credible allies with concise facts", idealRank: 2, effects: { "network-trust": 6, credibility: 3 } },
          { id: "statement", label: "Issue a short factual statement without rage", idealRank: 3, effects: { credibility: 4, focus: 2 } },
          { id: "doomscroll", label: "Read every mention and quote-post", idealRank: 5, effects: { focus: -8, "mental-stamina": -6 } },
          { id: "counterattack", label: "Attack the biggest account spreading it", idealRank: 4, effects: { credibility: -4, "network-trust": -3, resilience: -2 } },
        ],
        rationale: "Not every attack should be fought at full volume in public.",
      },
      {
        id: "st2-trust-break",
        title: "Your Network Starts to Thin",
        type: "decision",
        year: 2039,
        difficulty: 3,
        timed: false,
        briefing: {
          objective: "Choose a response to slow reputational decay inside your network.",
          constraints: ["No single incident explains it", "People still like you but trust your follow-through less", "Repair takes time"],
          resources: ["You can change your behavior", "Some bridges are still open", "You cannot fake consistency for long"],
          scoring: "The strongest answer aligns narrative repair with behavior repair.",
          outcomes: {
            success: "You regain trust by changing the underlying pattern.",
            partial: "You improve optics faster than substance.",
            failure: "You rationalize decline until opportunity flow dries up.",
          },
        },
        scenario: "Introductions, replies, and opportunities have slowed. You were not malicious. You were scattered, late, overpromising, and intermittently unavailable during stress.",
        options: [
          {
            id: "repair-system",
            title: "Shrink commitments, become radically reliable, and rebuild slowly",
            description: "Fewer promises, cleaner execution, repeated proof.",
            effects: { credibility: 9, "network-trust": 10, focus: 4, resilience: 2 },
            tags: ["boring", "correct"],
            rationale: "Trust usually returns through consistency, not explanation.",
          },
          {
            id: "rebrand",
            title: "Launch a polished personal rebrand campaign",
            description: "Better optics, same underlying instability.",
            effects: { credibility: -3, "network-trust": -2, focus: -1, adaptability: 2 },
            tags: ["surface-level"],
            rationale: "Image management cannot permanently outrun pattern memory.",
          },
          {
            id: "new-circle",
            title: "Abandon old network and chase new circles",
            description: "Fresh start, but you may carry the same weakness forward.",
            effects: { adaptability: 6, "network-trust": -5, credibility: -1, resilience: 1 },
            tags: ["escape"],
            rationale: "Sometimes necessary, often avoidance.",
          },
        ],
      },
      {
        id: "st3-ai-fake",
        title: "Authenticity in the Age of Synthetic Everything",
        type: "contradiction",
        year: 2042,
        difficulty: 4,
        timed: true,
        timeLimit: 60,
        briefing: {
          objective: "Pick the three strongest signals that a piece of information should not be trusted yet.",
          constraints: ["Choose exactly 3", "This is not about certainty, but disciplined skepticism", "Sophisticated fakes now mimic surface professionalism"],
          resources: ["You can inspect source patterns", "You have no privileged insider access", "Your decision may affect others"],
          scoring: "You score higher by looking for verification structure, not vibes.",
          outcomes: {
            success: "You avoid becoming a relay station for polished falsehoods.",
            partial: "You catch some warning signs but still over-trust presentation quality.",
            failure: "You outsource truth to aesthetics or consensus pressure.",
          },
        },
        scenario: "A dossier, audio clip, and screenshot bundle appears to expose a public figure and several companies. It is convincing enough to spread, uncertain enough to ruin lives if wrong.",
        correctIds: ["source-chain", "independent", "timing-incentive"],
        choices: [
          { id: "source-chain", title: "The provenance chain is broken or unverifiable", description: "No clean path from origin to current artifact." },
          { id: "independent", title: "No independent verification exists beyond accounts citing each other", description: "Circular amplification is not confirmation." },
          { id: "timing-incentive", title: "The release timing benefits a specific actor during a high-stakes moment", description: "Incentive does not prove falsity, but increases caution needs." },
          { id: "highres", title: "The media assets look high resolution", description: "High polish is not trust." },
          { id: "viral", title: "Many large accounts are posting it", description: "Virality is not validation." },
          { id: "expert-tone", title: "The thread uses technical language", description: "Sophisticated language can still be manipulative." },
        ],
        rationale: "The next misinformation era is not obvious nonsense. It is plausible ambiguity at scale.",
      },
    ],
    debrief: "Reputation is not the same as image. Image is what people feel briefly. Reputation is what they predict you will do when it matters.",
  },
  {
    id: "crisis-leadership",
    title: "Crisis Leadership",
    intro: "Under stress, leadership is less about charisma and more about sequencing, triage, and clarity under incomplete facts.",
    levels: [
      {
        id: "cl1-infra-failure",
        title: "Regional Grid Failure",
        type: "allocation",
        year: 2041,
        difficulty: 4,
        timed: true,
        timeLimit: 55,
        briefing: {
          objective: "Allocate eight response units across the first four hours of a grid failure affecting your team and local operations.",
          constraints: ["You have only 8 units", "Underfunding one area creates second-order risk", "Information is partial"],
          resources: ["Small team", "One backup site", "Mixed staff capability"],
          scoring: "The strongest allocation protects life, communication, decision quality, and recovery sequence.",
          outcomes: {
            success: "You stabilize people and the operating picture before optimizing output.",
            partial: "You keep moving but create avoidable confusion.",
            failure: "You confuse motion and control while critical basics fail.",
          },
        },
        scenario: "A severe heat wave causes rolling grid failure. Your team is partly remote, partly on-site, and one critical supplier is offline.",
        pool: 8,
        choices: [
          { id: "people", label: "Staff safety and status check", cost: 2, effects: { resilience: 5, "network-trust": 6, credibility: 2 } },
          { id: "comms", label: "Single source of truth communication channel", cost: 1, effects: { credibility: 5, focus: 3 } },
          { id: "backup", label: "Backup ops migration", cost: 2, effects: { adaptability: 6, "financial-buffer": 2 } },
          { id: "triage", label: "Client / mission triage matrix", cost: 2, effects: { "strategic-clarity": 7, credibility: 3 } },
          { id: "image", label: "External brand messaging polish", cost: 1, effects: { credibility: -2, focus: -1 } },
          { id: "rest-cycle", label: "Leader rotation and rest protocol", cost: 1, effects: { "mental-stamina": 5, focus: 2 } },
        ],
        rationale: "In crisis, clarity is a resource, not a mood.",
      },
      {
        id: "cl2-medical-shortage",
        title: "No Perfect Option Triage",
        type: "decision",
        year: 2044,
        difficulty: 5,
        timed: false,
        briefing: {
          objective: "Choose a triage policy when resources are insufficient and every option carries moral cost.",
          constraints: ["There is no clean answer", "Fairness, outcomes, and legitimacy can diverge", "You will have to explain your choice publicly"],
          resources: ["Trusted but exhausted team", "Incomplete data", "Very limited supplies"],
          scoring: "You score higher for preserving ethical coherence and transparent decision logic.",
          outcomes: {
            success: "You choose a defensible framework and communicate it honestly.",
            partial: "You get workable outcomes but erode legitimacy.",
            failure: "You choose ad hoc emotional favoritism with no stable principle.",
          },
        },
        scenario: "A local systems shock creates a temporary medical supply shortage. Three groups need support. Demand exceeds supply by a wide margin.",
        options: [
          {
            id: "transparent-framework",
            title: "Use a transparent severity-and-benefit framework with public reasoning",
            description: "Hard emotionally, but consistent and reviewable.",
            effects: { "ethical-consistency": 10, credibility: 7, "mental-stamina": -2, "network-trust": 3 },
            tags: ["legitimate", "painful"],
            rationale: "In severe scarcity, legitimacy comes from principled process as much as outcome.",
          },
          {
            id: "quiet-favors",
            title: "Quietly favor people with influence or future strategic value",
            description: "Pragmatic on paper, corrosive in culture.",
            effects: { "financial-buffer": 2, credibility: -10, "ethical-consistency": -12, "network-trust": -7 },
            tags: ["expedient", "corrosive"],
            rationale: "Once selective favoritism is visible, trust collapses faster than utility gains.",
          },
          {
            id: "first-come",
            title: "Use first-come, first-served to avoid responsibility",
            description: "Simple, legible, often morally lazy.",
            effects: { credibility: -3, "ethical-consistency": -4, focus: 1, "strategic-clarity": -4 },
            tags: ["neutral-looking"],
            rationale: "Avoiding judgment is still a judgment.",
          },
        ],
      },
      {
        id: "cl3-second-order",
        title: "The Recovery Phase Is Where Leaders Fail",
        type: "priority",
        year: 2046,
        difficulty: 5,
        timed: true,
        timeLimit: 55,
        briefing: {
          objective: "Rank your recovery priorities after the immediate crisis passes.",
          constraints: ["You must rank all five", "Early recovery habits shape whether damage repeats", "People are tired and want false closure"],
          resources: ["Temporary calm", "Visible fatigue", "Some political cover for changes"],
          scoring: "You score higher for preventing recurrence and burnout, not just declaring victory.",
          outcomes: {
            success: "You turn crisis lessons into durable structural improvement.",
            partial: "You restore operations but fail to repair deep vulnerabilities.",
            failure: "You celebrate survival and recreate the exact preconditions of failure.",
          },
        },
        scenario: "The immediate incident is over. Pressure to move on is intense. That is exactly what makes the next mistake likely.",
        items: [
          { id: "after-action", label: "Run an honest after-action review with uncomfortable facts", idealRank: 1, effects: { "strategic-clarity": 7, credibility: 3 } },
          { id: "people", label: "Set recovery load and rest boundaries for exhausted staff", idealRank: 2, effects: { "mental-stamina": 6, "network-trust": 5 } },
          { id: "fixes", label: "Prioritize 2-3 structural fixes with owners and deadlines", idealRank: 3, effects: { adaptability: 5, resilience: 4 } },
          { id: "press", label: "Maximize external narrative of flawless handling", idealRank: 5, effects: { credibility: -4, focus: -2 } },
          { id: "resume", label: "Resume full normal output as soon as possible", idealRank: 4, effects: { "financial-buffer": 1, "health-stability": -5 } },
        ],
        rationale: "Recovery work is where learning is either institutionalized or wasted.",
      },
    ],
    debrief: "Leadership in shocks is often the ability to remain ethically structured when speed and fear are pressuring you toward shortcuts.",
  },
  {
    id: "strategic-survival",
    title: "2050 Strategic Survival",
    intro: "The final game is not about personal optimization alone. It is about choosing what kind of future you are helping build while still surviving inside it.",
    levels: [
      {
        id: "ss1-city-choice",
        title: "Where Do You Anchor?",
        type: "decision",
        year: 2047,
        difficulty: 4,
        timed: false,
        briefing: {
          objective: "Choose a 10-year base strategy under climate, infrastructure, and political uncertainty.",
          constraints: ["No city is perfect", "You must weigh community, cost, climate, and institutional quality", "A wrong anchor compounds slowly"],
          resources: ["Portable work", "Family considerations", "Moderate capital"],
          scoring: "You gain more for robust systems thinking than for glamour or ideology.",
          outcomes: {
            success: "You choose a base with survivability, social fabric, and adaptive capacity.",
            partial: "You optimize one axis while ignoring another crucial one.",
            failure: "You anchor in a place that flatters your identity but weakens your future options.",
          },
        },
        scenario: "By 2047, location strategy is no longer lifestyle decoration. It shapes energy access, water security, social trust, and your family’s stress baseline.",
        options: [
          {
            id: "resilient-mid",
            title: "Choose a less glamorous but institutionally stable region",
            description: "Moderate opportunities, stronger resilience fundamentals, lower fragility.",
            effects: { resilience: 8, "financial-buffer": 5, "network-trust": 4, "strategic-clarity": 7 },
            tags: ["robust"],
            rationale: "Boring systems with working infrastructure often beat fashionable fragility.",
          },
          {
            id: "super-city",
            title: "Stay in a global megacity with peak opportunity density",
            description: "High upside, high stress, high climate and cost exposure.",
            effects: { credibility: 3, adaptability: 5, "financial-buffer": -8, "health-stability": -4 },
            tags: ["high-upside", "high-friction"],
            rationale: "Dense opportunity can still be strategically wrong if your buffers are thin.",
          },
          {
            id: "remote-isolation",
            title: "Move to a remote low-cost zone with weak institutions",
            description: "Cheap now, potentially brittle later.",
            effects: { "financial-buffer": 7, "network-trust": -6, adaptability: -2, resilience: -1 },
            tags: ["cheap", "thin-support"],
            rationale: "Cost savings without institutional quality can be false economy.",
          },
        ],
      },
      {
        id: "ss2-governance-choice",
        title: "The Efficient Wrong",
        type: "contradiction",
        year: 2049,
        difficulty: 5,
        timed: true,
        timeLimit: 60,
        briefing: {
          objective: "Choose the three governance principles most likely to preserve long-term human agency.",
          constraints: ["Choose exactly 3", "Some options are efficient but strategically dangerous", "You must think beyond personal convenience"],
          resources: ["You have influence in a civic coalition", "Public sentiment is divided", "Short-term fear is high"],
          scoring: "You score higher by identifying durable governance principles, not just fast fixes.",
          outcomes: {
            success: "You favor structures that preserve agency and resilience over seductive control.",
            partial: "You see some long-term risk but still overvalue convenience.",
            failure: "You optimize for order in ways that hollow out freedom and adaptability.",
          },
        },
        scenario: "A coalition is debating how society should govern high-impact AI and infrastructure systems after multiple shocks. The proposals differ in efficiency, accountability, and human autonomy.",
        correctIds: ["human-override", "auditability", "distributed-capacity"],
        choices: [
          { id: "human-override", title: "Preserve meaningful human override in high-impact systems", description: "Humans remain accountable for last-resort judgment." },
          { id: "auditability", title: "Require auditability and contestability of critical automated decisions", description: "Citizens need review mechanisms, not blind authority." },
          { id: "distributed-capacity", title: "Avoid over-centralizing critical capacity into a few actors", description: "Redundancy and distribution improve resilience." },
          { id: "total-optimization", title: "Allow central systems to optimize most decisions for efficiency", description: "Appealing under stress, dangerous if misaligned." },
          { id: "obedience-scores", title: "Link access and privileges to behavioral compliance scoring", description: "Order rises, freedom and dissent erode." },
          { id: "opaque-experts", title: "Trust closed expert systems because the public is confused", description: "Competence matters, opacity still carries abuse risk." },
        ],
        rationale: "The future can become legible and still become less human.",
      },
      {
        id: "ss3-legacy",
        title: "What Did Your Pattern Become?",
        type: "decision",
        year: 2050,
        difficulty: 5,
        timed: false,
        briefing: {
          objective: "Choose a final 2050 strategy that best reflects what kind of person and system-builder you became.",
          constraints: ["This is path-dependent", "The best ending is not the most comfortable one", "You must integrate tradeoffs across the whole run"],
          resources: ["Your accumulated strengths and scars", "Whatever trust and buffer you preserved", "A clearer view of what future costs really mean"],
          scoring: "This final decision weighs your current stats and whether your pattern is coherent.",
          outcomes: {
            success: "You choose a path aligned with both survival and principled stewardship.",
            partial: "You survive but narrow your future meaning or flexibility.",
            failure: "You optimize for immediate security in ways that betray your deeper long-term structure.",
          },
        },
        scenario: "By 2050, your choices have made you into a certain kind of operator. Now you must decide how to spend the next decade: extracting value, insulating your tribe, building resilient institutions, or withdrawing.",
        options: [
          {
            id: "build-institutions",
            title: "Invest in building resilient local institutions and talent pipelines",
            description: "Slower payoff, larger legacy, requires credibility and stamina.",
            effects: { "strategic-clarity": 8, "ethical-consistency": 7, "network-trust": 7, resilience: 5 },
            tags: ["legacy", "service"],
            rationale: "Durable futures are built through competent institutions, not only individual escape.",
          },
          {
            id: "private-fortress",
            title: "Maximize private insulation for yourself and your inner circle",
            description: "Rational in narrow terms, socially corrosive in aggregate.",
            effects: { "financial-buffer": 8, "network-trust": -6, "ethical-consistency": -4, resilience: 1 },
            tags: ["protective", "narrow"],
            rationale: "Personal safety can become strategic shrinking.",
          },
          {
            id: "opportunistic-arb",
            title: "Exploit volatility aggressively wherever returns are highest",
            description: "High gains, identity drift risk, and compounding moral compromise.",
            effects: { "financial-buffer": 10, credibility: -5, "ethical-consistency": -8, "strategic-clarity": -3 },
            tags: ["lucrative", "corrosive"],
            rationale: "Some win the future financially while becoming unfit to trust.",
          },
        ],
      },
    ],
    debrief: "Strategic survival is not only staying alive. It is deciding what forms of strength you refuse to sacrifice even when the future gets expensive.",
  },
];

export const UNLOCK_RULES = [
  { modeId: "hard", description: "Finish one full run." },
  { modeId: "low-information", description: "Reach average score of 60+ on any run." },
  { modeId: "high-pressure", description: "Finish two runs." },
  { modeId: "ethics-stress-test", description: "Finish a run with Ethical Consistency average above 60." },
  { modeId: "long-horizon-strategist", description: "Finish a run with Strategic Clarity average above 65." },
];
